@startuml

left to right direction

hide circle

title Діаграма програмних класів (Oracle PL/SQL)

Class Місцеположення {
    -номер_місцеположення number(4)
    -назва varchar(20)
    +Місцеположення(p_назва varchar)
    +встановити_назву(p_номер number, p_назва varchar)
    +отримати_номер()
    +отримати_назву()
    +вивести()
}

Class Відділ {
    -номер_відділу number(4)
    -назва varchar(20)
    -місцеположення Місцеположення
    +Відділ(p_назва varchar, p_місцеположення Місцеположення)
    +встановити_назву(p_номер number, p_назва varchar)
    +встановити_місцеположення(p_номер number, p_місцеположення Місцеположення)
    +отримати_номер()
    +отримати_назву()
    +вивести()
}

Class Працівник {
    #номер_працівника number(4)
    #ім'я varchar(20)
    #посада varchar(20)
    #дата_найму Date
    #зарплата number(8,2)
    #бонус number(8,2)
    #відділ Відділ
    +вивести()
    +встановити_посаду(p_посада varchar)
    +встановити_відділ(p_відділ Відділ)
    +отримати_посаду()
    +отримати_відділ()
}

Class Керівник {
    -список_працівників Список_Працівників
    +додати_працівника(p_працівник Працівник)
    +видалити_працівника(p_номер number)
    +отримати_список()
}

Працівник <|-- Керівник

Працівник "1" <-- "+" Керівник : управляє

Працівник "+" --> "1" Відділ : працює_в

Місцеположення "1" o-- "+" Відділ : розташований_в

@enduml
